config/routes.rb
Depot4::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items
	has_many :orders, through: :line_items
	
	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true

	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
		message: 'URL должен указывать на изображение формата GIF, JPG или PNG'
	}

	validates :title, length: {minimum: 10,
		message: 'название долно иметь не менее 10 символов'}

	def self.latest
		Product.order(:updated_at).latest
	end

	

	before_destroy :ensure_not_referenced_by_any_line_item

	private

	#убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]



    def who_bought
      @product = Product.find(params[:id])
      #@latest_order = @product.orders.order(:updated_at).last
      #if stale?(@latest_order)
        respond_to do |format|
          format.atom
        end
      #end      
    end


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    respond_to do |format|
      format.html
      format.xml { render xml: @product.to_xml }
      format.yaml { render text: @product.to_yaml }
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
== form_for(@product) do |f|
  - if @product.errors.any? 
    div id="error_explanation"
      h2 == pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      ul
      -@product.errors.full_messages.each do |message|
        li == message
  div class="field"
    == f.label :title
    br
    == f.text_field :title
  div class="field"
    == f.label :description
    br
    == f.text_area :description, rows: 6
  div class="field"
    == f.label :image_url
    br
    == f.text_field :image_url
  div class="field"
    == f.label :price
    br
    == f.text_field :price  
  div class="actions"
    == f.submit

app/views/products/edit.html.slim
h1 Editing Product

== render 'form'

== link_to 'Show', @product 
br
== link_to 'Back', products_path

app/views/products/index.html.slim
h1 Listing Products

table
  - @products.each do |product|
    tr class="cycle_color"
      td == image_tag(product.image_url, class: 'list_image')
      td class="list_description"
        dl
          dt == product.title
          dd == truncate(strip_tags(product.description), length: 80)
      td class="list_actions"
        == link_to 'Show', product
        br
        == link_to 'Edit', edit_product_path(product)
        br
        == link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

br

== link_to 'New Product', new_product_path 

app/views/products/new.html.slim
h1 New Product

== render 'form'

== link_to 'Back', products_path 

app/views/products/show.html.slim
- if notice 
	p id="notice" == notice
	
p
	strong Title:
	== @product.title 

p
	strong Description:
	== @product.description 

p
	strong Image url:
	== @product.image_url

p
	strong Price:
	== @product.price 

== link_to 'Edit', edit_product_path(@product)
br
== link_to 'Back', products_path 