config/routes.rb
Depot4::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart

  def total_price
  	#product.price * quantity  
  	price * quantity	
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authorize, only: :create
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    #@line_item = @cart.add_product(product.id)
    #поменяно на нижеидущее  
    @line_item = @cart.add_product(product.id, product.price)

    respond_to do |format|
      if @line_item.save
        session[:counter] = 0
        format.html { redirect_to store_url }
        format.js { @cuurent_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy

    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
    

    #@line_item = LineItem.find(params[:id])
    #@line_item.destroy

    #respond_to do |format|

     # if LineItem.find_by_cart_id(@line_item.cart_id).nil? 
      #  format.html { redirect_to store_url, 
       #      notice: 'Your cart is currently empty' }
      #else
        #как остацца на странице?
       # format.html { redirect_to set_cart,
       #    notice: 'Line item removed' }
     # end

      #format.json { head :ok }
    #end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # Не доверяйте параметрам, полученным из этого жуткого интернета,
    #разркшайте использование только пустого списка
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.slim
== form_for(@line_item) do |f| 
  - if @line_item.errors.any? 
    div id="error_explanation"
      h2 == pluralize(@line_item.errors.count, "error")
        prohibited this line_item from being saved:
      ul
      - @line_item.errors.full_messages.each do |message|
        li == message
  div class="field"
    == f.label :product_id 
    br
    == f.text_field :product_id
  div class="field"
    == f.label :cart_id 
    br
    == f.text_field :cart_id 
  div class="actions"
    == f.submit

app/views/line_items/_line_item.html.slim
- if line_item == @current_item 
	tr id="current_item"
- else 
	tr
	
	td == line_item.quantity 
	td &times;
	td == line_item.product.title 
	td class="item_price" == number_to_currency(line_item.total_price)

app/views/line_items/_line_item.text.slim
== sprintf("%2d x %s",
			line_item.quantity,
			truncate(line_item.product.title, length: 50))

app/views/line_items/create.js.erb
$('#notice').hide();

if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= escape_javascript render(@cart) %>");

$('#current_item').css({'background-color':'#88ff88'}).
animate({'background-color':'#114411'}, 1000);

app/views/line_items/edit.html.slim
h1 Editing Line Item

== render 'form' 

== link_to 'Show', @line_item
br
== link_to 'Back', line_items_path

app/views/line_items/index.html.slim
- if notice 
  p id="notice" == notice 

h1 Listing Line Items

table
  thead
    tr
      th Product
      th Cart
      th colspan="3"
  tbody
  - @line_items.each do |line_item|
    tr
      td == line_item.product
      td == line_item.cart
      td == link_to 'Show', line_item
      td == link_to 'Edit', edit_line_item_path(line_item)
      td == link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } 
     
br

== link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.slim
h1 New Line Item

== render 'form' 

== link_to 'Back', line_items_path 

app/views/line_items/show.html.slim
- if notice 
	p id="notice" == notice 

p
	strong Product:
	== @line_item.product 

p
	strong Cart:
	== @line_item.cart 

== link_to 'Edit', edit_line_item_path(@line_item)
br
== link_to 'Back', line_items_path