config/routes.rb
Depot4::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'

end

app/views/layouts/application.html.slim
doctype html
html
	head
		title Pragprog Books Online Store 
		== stylesheet_link_tag 'application', media: 'all'
		== javascript_include_tag 'application'
		== csrf_meta_tags 
	body class='<%= controller.controller_name %>'
		div id="banner"
			== image_tag("logo.png") 
			== @page_title || "Pragmatic Bookshelf " 
			== pluralize session[:counter], 'time' if session[:counter] >= 5 
		
		div id="columns"
			div id="side"
				- if @cart 
					== hidden_div_if(@cart.line_items.empty?, id: 'cart') do 
						== render @cart 
							
				ul
					li
						a href="#" Home
					li
						a href="#" Questions
					li
						a href="#" News
					li
						a href="#" Contact

				- if session[:user_id]  
					ul
						li == link_to 'Orders', orders_path 
						li == link_to 'Products', products_path 
						li == link_to 'Users', users_path 
						
					== button_to 'Logout', logout_path, method: :delete 
					
				p class="time" == Time.now  
			
			div id="main" class="products"
				== yield 